version: '3.8'
services:
  postgres:
    container_name: golang_pos_app
    image: postgres
    ports:
      - 7000:5432
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.docker/golang_pos_app/db_pos_app:/var/lib/postgresql/data